# syntax=docker/dockerfile:1

# build production app
FROM node:16-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install --production --silent
RUN npm -v

COPY . .
RUN npm run build

# build production env
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
