version: "3.7"
services:
  react-ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  nginx:
    image: nginx-alpine
    ports:
      - 80:80